name = "HoJBot"
uuid = "7918a2cc-0dd0-4d51-b3de-26cf4b7ed9a1"
authors = ["Tom Kwong <tomkwong@fb.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
